# Generated by Django 5.1.6 on 2025-03-22 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_chatmodel_userprofilemodel_delete_message'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ChatModel',
        ),
        migrations.DeleteModel(
            name='UserProfileModel',
        ),
    ]
