# Generated by Django 5.2.1 on 2025-06-02 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_user_bio_user_company_logo_user_company_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='company_logo',
        ),
        migrations.RemoveField(
            model_name='user',
            name='company_name',
        ),
        migrations.AddField(
            model_name='user',
            name='profile_bg',
            field=models.ImageField(blank=True, null=True, upload_to='profile_bg/'),
        ),
    ]
