# Generated by Django 5.2.1 on 2025-06-02 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_remove_user_company_logo_remove_user_company_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Company'), (2, 'Investor'), (3, 'Admin')], default=1),
        ),
    ]
