# Generated by Django 5.2.1 on 2025-06-17 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_chartdata_userchartselection'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='userDetail',
            field=models.TextField(blank=True, null=True),
        ),
    ]
